# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def solve():
    ans = 2
    fibonacci_seq = [1, 2]
    while fibonacci_seq[-1] <= 4000000:
        fibonacci_seq.append(sum([fibonacci_seq[-1], fibonacci_seq[-2]]))
        if fibonacci_seq[-1] % 2 == 0:
            ans += fibonacci_seq[-1]
    return ans

if __name__ == "__main__":
    print(solve())
